//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conditions {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Conditions.ExceptionMessages", typeof(ExceptionMessages).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} contains currently 1 element..
        /// </summary>
        internal static string CollectionContainsCurrently1Element {
            get {
                return ResourceManager.GetString("CollectionContainsCurrently1Element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} contains currently {1} elements..
        /// </summary>
        internal static string CollectionContainsCurrentlyXElements {
            get {
                return ResourceManager.GetString("CollectionContainsCurrentlyXElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is currently a null reference..
        /// </summary>
        internal static string CollectionIsCurrentlyANullReference {
            get {
                return ResourceManager.GetString("CollectionIsCurrentlyANullReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be empty.
        /// </summary>
        internal static string CollectionShouldBeEmpty {
            get {
                return ResourceManager.GetString("CollectionShouldBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should contain 1 element.
        /// </summary>
        internal static string CollectionShouldContain1Element {
            get {
                return ResourceManager.GetString("CollectionShouldContain1Element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should contain all of {1}.
        /// </summary>
        internal static string CollectionShouldContainAllOfX {
            get {
                return ResourceManager.GetString("CollectionShouldContainAllOfX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should contain at least one of {1}.
        /// </summary>
        internal static string CollectionShouldContainAtLeastOneOfX {
            get {
                return ResourceManager.GetString("CollectionShouldContainAtLeastOneOfX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should contain less than 1 element.
        /// </summary>
        internal static string CollectionShouldContainLessThan1Element {
            get {
                return ResourceManager.GetString("CollectionShouldContainLessThan1Element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should contain less than {1} elements.
        /// </summary>
        internal static string CollectionShouldContainLessThanXElements {
            get {
                return ResourceManager.GetString("CollectionShouldContainLessThanXElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should contain more than 1 element.
        /// </summary>
        internal static string CollectionShouldContainMoreThan1Element {
            get {
                return ResourceManager.GetString("CollectionShouldContainMoreThan1Element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should contain more than {1} elements.
        /// </summary>
        internal static string CollectionShouldContainMoreThanXElements {
            get {
                return ResourceManager.GetString("CollectionShouldContainMoreThanXElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should contain {1}.
        /// </summary>
        internal static string CollectionShouldContainX {
            get {
                return ResourceManager.GetString("CollectionShouldContainX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should contain {1} elements.
        /// </summary>
        internal static string CollectionShouldContainXElements {
            get {
                return ResourceManager.GetString("CollectionShouldContainXElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should contain {1} or less elements.
        /// </summary>
        internal static string CollectionShouldContainXOrLessElements {
            get {
                return ResourceManager.GetString("CollectionShouldContainXOrLessElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should contain {1} or more elements.
        /// </summary>
        internal static string CollectionShouldContainXOrMoreElements {
            get {
                return ResourceManager.GetString("CollectionShouldContainXOrMoreElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should not be empty.
        /// </summary>
        internal static string CollectionShouldNotBeEmpty {
            get {
                return ResourceManager.GetString("CollectionShouldNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should not contain 1 element.
        /// </summary>
        internal static string CollectionShouldNotContain1Element {
            get {
                return ResourceManager.GetString("CollectionShouldNotContain1Element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should not contain all of {1}.
        /// </summary>
        internal static string CollectionShouldNotContainAllOfX {
            get {
                return ResourceManager.GetString("CollectionShouldNotContainAllOfX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should not contain any of {1}.
        /// </summary>
        internal static string CollectionShouldNotContainAnyOfX {
            get {
                return ResourceManager.GetString("CollectionShouldNotContainAnyOfX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should not contain more than 1 element.
        /// </summary>
        internal static string CollectionShouldNotContainLessThan1Element {
            get {
                return ResourceManager.GetString("CollectionShouldNotContainLessThan1Element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should not contain less than {1} elements.
        /// </summary>
        internal static string CollectionShouldNotContainLessThanXElements {
            get {
                return ResourceManager.GetString("CollectionShouldNotContainLessThanXElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should not contain more than 1 element.
        /// </summary>
        internal static string CollectionShouldNotContainMoreThan1Element {
            get {
                return ResourceManager.GetString("CollectionShouldNotContainMoreThan1Element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should not contain more than {1} elements.
        /// </summary>
        internal static string CollectionShouldNotContainMoreThanXElements {
            get {
                return ResourceManager.GetString("CollectionShouldNotContainMoreThanXElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should not contain {1}.
        /// </summary>
        internal static string CollectionShouldNotContainX {
            get {
                return ResourceManager.GetString("CollectionShouldNotContainX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should not contain {1} elements.
        /// </summary>
        internal static string CollectionShouldNotContainXElements {
            get {
                return ResourceManager.GetString("CollectionShouldNotContainXElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should not contain {1} or less elements.
        /// </summary>
        internal static string CollectionShouldNotContainXOrLessElements {
            get {
                return ResourceManager.GetString("CollectionShouldNotContainXOrLessElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should not contain {1} or more elements.
        /// </summary>
        internal static string CollectionShouldNotContainXOrMoreElements {
            get {
                return ResourceManager.GetString("CollectionShouldNotContainXOrMoreElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified type {0} is not supported. The type must be concrete and have a public constructor with a single string argument..
        /// </summary>
        internal static string ExceptionTypeIsInvalid {
            get {
                return ResourceManager.GetString("ExceptionTypeIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{1}&apos; should hold for {0}.
        /// </summary>
        internal static string LambdaXShouldHoldForValue {
            get {
                return ResourceManager.GetString("LambdaXShouldHoldForValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcondition failed..
        /// </summary>
        internal static string PostconditionFailed {
            get {
                return ResourceManager.GetString("PostconditionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcondition &apos;{0}&apos; failed..
        /// </summary>
        internal static string PostconditionXFailed {
            get {
                return ResourceManager.GetString("PostconditionXFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be 1 character long.
        /// </summary>
        internal static string StringShouldBe1CharacterLong {
            get {
                return ResourceManager.GetString("StringShouldBe1CharacterLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be an empty string.
        /// </summary>
        internal static string StringShouldBeEmpty {
            get {
                return ResourceManager.GetString("StringShouldBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be longer or equal to 1 character.
        /// </summary>
        internal static string StringShouldBeLongerOrEqualTo1Character {
            get {
                return ResourceManager.GetString("StringShouldBeLongerOrEqualTo1Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be longer or equal to {1} characters.
        /// </summary>
        internal static string StringShouldBeLongerOrEqualToXCharacters {
            get {
                return ResourceManager.GetString("StringShouldBeLongerOrEqualToXCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be longer than 1 character.
        /// </summary>
        internal static string StringShouldBeLongerThan1Character {
            get {
                return ResourceManager.GetString("StringShouldBeLongerThan1Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be longer than {1} characters.
        /// </summary>
        internal static string StringShouldBeLongerThanXCharacters {
            get {
                return ResourceManager.GetString("StringShouldBeLongerThanXCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be null or an empty string.
        /// </summary>
        internal static string StringShouldBeNullOrEmpty {
            get {
                return ResourceManager.GetString("StringShouldBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be null, empty or consists only of white-space characters..
        /// </summary>
        internal static string StringShouldBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("StringShouldBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be shorter or equal to 1 character.
        /// </summary>
        internal static string StringShouldBeShorterOrEqualTo1Character {
            get {
                return ResourceManager.GetString("StringShouldBeShorterOrEqualTo1Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be shorter or equal to {1} characters.
        /// </summary>
        internal static string StringShouldBeShorterOrEqualToXCharacters {
            get {
                return ResourceManager.GetString("StringShouldBeShorterOrEqualToXCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be shorter than 1 character.
        /// </summary>
        internal static string StringShouldBeShorterThan1Character {
            get {
                return ResourceManager.GetString("StringShouldBeShorterThan1Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be shorter than {1} characters.
        /// </summary>
        internal static string StringShouldBeShorterThanXCharacters {
            get {
                return ResourceManager.GetString("StringShouldBeShorterThanXCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be {1} characters long.
        /// </summary>
        internal static string StringShouldBeXCharactersLong {
            get {
                return ResourceManager.GetString("StringShouldBeXCharactersLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should contain {1}.
        /// </summary>
        internal static string StringShouldContainX {
            get {
                return ResourceManager.GetString("StringShouldContainX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should end with {1}.
        /// </summary>
        internal static string StringShouldEndWithX {
            get {
                return ResourceManager.GetString("StringShouldEndWithX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should not be 1 character long.
        /// </summary>
        internal static string StringShouldNotBe1CharacterLong {
            get {
                return ResourceManager.GetString("StringShouldNotBe1CharacterLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should not be an empty string.
        /// </summary>
        internal static string StringShouldNotBeEmpty {
            get {
                return ResourceManager.GetString("StringShouldNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should not be null or an empty string.
        /// </summary>
        internal static string StringShouldNotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("StringShouldNotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should not be null, and empty string or consists only of white-space characters..
        /// </summary>
        internal static string StringShouldNotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("StringShouldNotBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should not be {1} characters long.
        /// </summary>
        internal static string StringShouldNotBeXCharactersLong {
            get {
                return ResourceManager.GetString("StringShouldNotBeXCharactersLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should not contain {1}.
        /// </summary>
        internal static string StringShouldNotContainX {
            get {
                return ResourceManager.GetString("StringShouldNotContainX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should not end with {1}.
        /// </summary>
        internal static string StringShouldNotEndWithX {
            get {
                return ResourceManager.GetString("StringShouldNotEndWithX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should not start with {1}.
        /// </summary>
        internal static string StringShouldNotStartWithX {
            get {
                return ResourceManager.GetString("StringShouldNotStartWithX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should start with {1}.
        /// </summary>
        internal static string StringShouldStartWithX {
            get {
                return ResourceManager.GetString("StringShouldStartWithX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The actual value is 1 character long..
        /// </summary>
        internal static string TheActualValueIs1CharacterLong {
            get {
                return ResourceManager.GetString("TheActualValueIs1CharacterLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The actual value is {1}..
        /// </summary>
        internal static string TheActualValueIsX {
            get {
                return ResourceManager.GetString("TheActualValueIsX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The actual value is {1} characters long..
        /// </summary>
        internal static string TheActualValueIsXCharactersLong {
            get {
                return ResourceManager.GetString("TheActualValueIsXCharactersLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be a number.
        /// </summary>
        internal static string ValueShouldBeANumber {
            get {
                return ResourceManager.GetString("ValueShouldBeANumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be between {1} and {2}.
        /// </summary>
        internal static string ValueShouldBeBetweenXAndY {
            get {
                return ResourceManager.GetString("ValueShouldBeBetweenXAndY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be equal to {1}.
        /// </summary>
        internal static string ValueShouldBeEqualToX {
            get {
                return ResourceManager.GetString("ValueShouldBeEqualToX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be false.
        /// </summary>
        internal static string ValueShouldBeFalse {
            get {
                return ResourceManager.GetString("ValueShouldBeFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be greater than or equal to {1}.
        /// </summary>
        internal static string ValueShouldBeGreaterThanOrEqualToX {
            get {
                return ResourceManager.GetString("ValueShouldBeGreaterThanOrEqualToX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be greater than {1}.
        /// </summary>
        internal static string ValueShouldBeGreaterThanX {
            get {
                return ResourceManager.GetString("ValueShouldBeGreaterThanX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be infinity.
        /// </summary>
        internal static string ValueShouldBeInfinity {
            get {
                return ResourceManager.GetString("ValueShouldBeInfinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be negative infinity.
        /// </summary>
        internal static string ValueShouldBeNegativeInfinity {
            get {
                return ResourceManager.GetString("ValueShouldBeNegativeInfinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be null.
        /// </summary>
        internal static string ValueShouldBeNull {
            get {
                return ResourceManager.GetString("ValueShouldBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be of type {1}.
        /// </summary>
        internal static string ValueShouldBeOfTypeX {
            get {
                return ResourceManager.GetString("ValueShouldBeOfTypeX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be positive infinity.
        /// </summary>
        internal static string ValueShouldBePositiveInfinity {
            get {
                return ResourceManager.GetString("ValueShouldBePositiveInfinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be smaller than or equal to {1}.
        /// </summary>
        internal static string ValueShouldBeSmallerThanOrEqualToX {
            get {
                return ResourceManager.GetString("ValueShouldBeSmallerThanOrEqualToX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be smaller than {1}.
        /// </summary>
        internal static string ValueShouldBeSmallerThanX {
            get {
                return ResourceManager.GetString("ValueShouldBeSmallerThanX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be true.
        /// </summary>
        internal static string ValueShouldBeTrue {
            get {
                return ResourceManager.GetString("ValueShouldBeTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be unequal to {1}.
        /// </summary>
        internal static string ValueShouldBeUnequalToX {
            get {
                return ResourceManager.GetString("ValueShouldBeUnequalToX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be valid.
        /// </summary>
        internal static string ValueShouldBeValid {
            get {
                return ResourceManager.GetString("ValueShouldBeValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should not be a number.
        /// </summary>
        internal static string ValueShouldNotBeANumber {
            get {
                return ResourceManager.GetString("ValueShouldNotBeANumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should not be between {1} and {2}.
        /// </summary>
        internal static string ValueShouldNotBeBetweenXAndY {
            get {
                return ResourceManager.GetString("ValueShouldNotBeBetweenXAndY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should not be greater than or equal to {1}.
        /// </summary>
        internal static string ValueShouldNotBeGreaterThanOrEqualToX {
            get {
                return ResourceManager.GetString("ValueShouldNotBeGreaterThanOrEqualToX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should not be greater than {1}.
        /// </summary>
        internal static string ValueShouldNotBeGreaterThanX {
            get {
                return ResourceManager.GetString("ValueShouldNotBeGreaterThanX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should not be infinity.
        /// </summary>
        internal static string ValueShouldNotBeInfinity {
            get {
                return ResourceManager.GetString("ValueShouldNotBeInfinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should not be negative infinity.
        /// </summary>
        internal static string ValueShouldNotBeNegativeInfinity {
            get {
                return ResourceManager.GetString("ValueShouldNotBeNegativeInfinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should not be null.
        /// </summary>
        internal static string ValueShouldNotBeNull {
            get {
                return ResourceManager.GetString("ValueShouldNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should not be of type {1}.
        /// </summary>
        internal static string ValueShouldNotBeOfTypeX {
            get {
                return ResourceManager.GetString("ValueShouldNotBeOfTypeX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should not be positive infinity.
        /// </summary>
        internal static string ValueShouldNotBePositiveInfinity {
            get {
                return ResourceManager.GetString("ValueShouldNotBePositiveInfinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should not be smaller than or equal to {1}.
        /// </summary>
        internal static string ValueShouldNotBeSmallerThanOrEqualToX {
            get {
                return ResourceManager.GetString("ValueShouldNotBeSmallerThanOrEqualToX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should not be smaller than {1}.
        /// </summary>
        internal static string ValueShouldNotBeSmallerThanX {
            get {
                return ResourceManager.GetString("ValueShouldNotBeSmallerThanX", resourceCulture);
            }
        }
    }
}
